target/riscv: fix compilation errors due to -Werror=implicit-fallthrough
-Werror=implicit-fallthrough appears to correctly catch missing
break statements in src/target/riscv/riscv-011.c:

src/target/riscv/riscv-011.c: In function ‘slot_offset’:
src/target/riscv/riscv-011.c:238:4: error: this statement may fall through [-Werror=implicit-fallthrough=]
    switch (slot) {
    ^~~~~~
src/target/riscv/riscv-011.c:243:3: note: here
   case 64:
   ^~~~

Fix by inserting break statements for each arm of the outer switch
statement.